// <auto-generated />
namespace BITCollege_CS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_NextUniqueNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_NextUniqueNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202310270347230_added_NextUniqueNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
